name: livekit_example
description: Example app that uses LiveKit Flutter SDK
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  flutter_background: ^1.1.0
  permission_handler: ^10.2.0
  provider: ^6.0.1
  logging: ^1.0.1
  shared_preferences: ^2.0.7
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  system_theme: ^2.3.1
  flutter_acrylic: ^1.0.0+2
  another_flushbar: ^1.12.30
  socket_io_client: ^2.0.3+1
  stacked_notification_cards: ^0.1.0-dev.4  
  fluent_ui:
    git:
      url: https://github.com/bagusandrewijaya/custom_fluentUI.git
      ref: main
      
  livekit_client:
    path: ../
  window_manager: ^0.3.7
  go_router: ^12.1.1
  url_launcher: ^6.2.1
  uuid: ^3.0.5
  floating_chat_button: ^1.0.1
  glassmorphism: ^3.0.0
  toastification: ^1.0.0

    # git:
    #   url: https://github.com/livekit/client-sdk-flutter
    #   ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/
